server {
    listen 80;

    # Все обычные запросы отдаем фронтенду
    location / {
        proxy_pass http://frontend:80;
    }

    # Все запросы к API перекидываем бэкенду
    location /api/ {
        proxy_pass http://backend:8000;
    }
}